table mart_contract_leaders
	lineageTag: 1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d

	measure 'Leader Price' = MAX(mart_contract_leaders[last_trade_price])
		formatString: 0.00%
		lineageTag: 2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e

	column contract_id
		dataType: string
		lineageTag: 3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f
		summarizeBy: none
		sourceColumn: contract_id

		annotation SummarizationSetBy = Automatic

	column contract_name
		dataType: string
		lineageTag: 4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a
		summarizeBy: none
		sourceColumn: contract_name

		annotation SummarizationSetBy = Automatic

	column market_id
		dataType: string
		lineageTag: 5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b
		summarizeBy: none
		sourceColumn: market_id

		annotation SummarizationSetBy = Automatic

	column market_name
		dataType: string
		lineageTag: 6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c
		summarizeBy: none
		sourceColumn: market_name

		annotation SummarizationSetBy = Automatic

	column last_trade_price
		dataType: double
		lineageTag: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d
		summarizeBy: sum
		sourceColumn: last_trade_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column last_close_price
		dataType: double
		lineageTag: 8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e
		summarizeBy: sum
		sourceColumn: last_close_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column price_change_abs
		dataType: double
		lineageTag: 9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f
		summarizeBy: sum
		sourceColumn: price_change_abs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rank_by_price
		dataType: int64
		formatString: 0
		lineageTag: 0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a
		summarizeBy: sum
		sourceColumn: rank_by_price

		annotation SummarizationSetBy = Automatic

	column rank_by_movement
		dataType: int64
		formatString: 0
		lineageTag: 1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b
		summarizeBy: sum
		sourceColumn: rank_by_movement

		annotation SummarizationSetBy = Automatic

	column extraction_ts
		dataType: dateTime
		formatString: General Date
		lineageTag: 2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c
		summarizeBy: none
		sourceColumn: extraction_ts

		annotation SummarizationSetBy = Automatic

	partition mart_contract_leaders = m
		mode: import
		source =
				let
				    Origen = Odbc.DataSource("dsn=duckdb2", [HierarchicalNavigation=true]),
				    predictit_Database = Origen{[Name="predictit",Kind="Database"]}[Data],
				    main_marts_Schema = predictit_Database{[Name="main_marts",Kind="Schema"]}[Data],
				    mart_contract_leaders_Table = main_marts_Schema{[Name="mart_contract_leaders",Kind="Table"]}[Data]
				in
				    mart_contract_leaders_Table

	annotation PBI_ResultType = Table

