table mart_top_movers
	lineageTag: aa1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d

	measure 'Top Gainer Name' = CALCULATE(MAX(mart_top_movers[contract_name]), TOPN(1, ALL(mart_top_movers), mart_top_movers[change_abs], DESC), mart_top_movers[direction] = "GAINER")
		lineageTag: bb2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e

	measure 'Max Change 24H' = MAX(mart_top_movers[change_abs])
		formatString: 0.00%
		lineageTag: cc3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f

	measure 'Mayor Gainer 24h' = MAX(mart_top_movers[change_pct])
		formatString: 0.00%
		lineageTag: 3c333333-3333-4333-8333-333333333331

	measure 'Mayor Loser 24h' = MIN(mart_top_movers[change_pct])
		formatString: 0.00%
		lineageTag: 3c333333-3333-4333-8333-333333333332

	measure 'Precio Actual' = MAX(mart_top_movers[price_now])
		formatString: 0.000
		lineageTag: 3c333333-3333-4333-8333-333333333333

	measure 'Precio 24h' = MAX(mart_top_movers[price_24h_ago])
		formatString: 0.000
		lineageTag: 3c333333-3333-4333-8333-333333333334

	measure 'Cambio 24h' = MAX(mart_top_movers[change_pct])
		formatString: 0.00%
		lineageTag: 3c333333-3333-4333-8333-333333333335

	column contract_id
		dataType: string
		lineageTag: dd4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a
		summarizeBy: none
		sourceColumn: contract_id

		annotation SummarizationSetBy = Automatic

	column contract_name
		dataType: string
		lineageTag: ee5f6a7b-8c9d-0e1f-2a3b-4c5d6e7f8a9b
		summarizeBy: none
		sourceColumn: contract_name

		annotation SummarizationSetBy = Automatic

	column market_id
		dataType: string
		lineageTag: ff6a7b8c-9d0e-1f2a-3b4c-5d6e7f8a9b0c
		summarizeBy: none
		sourceColumn: market_id

		annotation SummarizationSetBy = Automatic

	column market_name
		dataType: string
		lineageTag: a17b8c9d-0e1f-2a3b-4c5d-6e7f8a9b0c1d
		summarizeBy: none
		sourceColumn: market_name

		annotation SummarizationSetBy = Automatic

	column price_now
		dataType: double
		lineageTag: b28c9d0e-1f2a-3b4c-5d6e-7f8a9b0c1d2e
		summarizeBy: sum
		sourceColumn: price_now

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column price_24h_ago
		dataType: double
		lineageTag: c39d0e1f-2a3b-4c5d-6e7f-8a9b0c1d2e3f
		summarizeBy: sum
		sourceColumn: price_24h_ago

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column change_abs
		dataType: double
		lineageTag: d40e1f2a-3b4c-5d6e-7f8a-9b0c1d2e3f4a
		summarizeBy: sum
		sourceColumn: change_abs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column change_pct
		dataType: double
		lineageTag: e51f2a3b-4c5d-6e7f-8a9b-0c1d2e3f4a5b
		summarizeBy: sum
		sourceColumn: change_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column direction
		dataType: string
		lineageTag: f62a3b4c-5d6e-7f8a-9b0c-1d2e3f4a5b6c
		summarizeBy: none
		sourceColumn: direction

		annotation SummarizationSetBy = Automatic

	column rank_gainer
		dataType: int64
		formatString: 0
		lineageTag: a73b4c5d-6e7f-8a9b-0c1d-2e3f4a5b6c7d
		summarizeBy: sum
		sourceColumn: rank_gainer

		annotation SummarizationSetBy = Automatic

	column rank_loser
		dataType: int64
		formatString: 0
		lineageTag: b84c5d6e-7f8a-9b0c-1d2e-3f4a5b6c7d8e
		summarizeBy: sum
		sourceColumn: rank_loser

		annotation SummarizationSetBy = Automatic

	column extraction_ts
		dataType: dateTime
		formatString: General Date
		lineageTag: c95d6e7f-8a9b-0c1d-2e3f-4a5b6c7d8e9f
		summarizeBy: none
		sourceColumn: extraction_ts

		annotation SummarizationSetBy = Automatic

	partition mart_top_movers = m
		mode: import
		source =
				let
				    Origen = Odbc.DataSource("dsn=duckdb2", [HierarchicalNavigation=true]),
				    predictit_Database = Origen{[Name="predictit",Kind="Database"]}[Data],
				    main_marts_Schema = predictit_Database{[Name="main_marts",Kind="Schema"]}[Data],
				    mart_top_movers_Table = main_marts_Schema{[Name="mart_top_movers",Kind="Table"]}[Data]
				in
				    mart_top_movers_Table

	annotation PBI_ResultType = Table

