name: predictit_dbt
version: '1.0.0'
config-version: 2

profile: predictit_dbt

model-paths: ["models"]
macro-paths: ["macros"]

models:
  predictit_dbt:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
